name: WindChat
version: ${project.version}
description: WindChat is a plugin for the Spout server that provides configurable chat formats.
author: Windwaker
website: http://github.com/W1ndwaker/WindChat
main: net.windwaker.chat.WindChat
platform: BOTH